config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'test1/index'

  get 'page/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources:posts do
    resources:comments
  end
  
  resources:pages
  resources:results
  resources:test2s
  resources:users
  
  # いらないけどトップページを新しく作るの面倒だからこのルーティングは残しておく
  root 'test2s#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3, message: 'Too short to post!' }
  validates :body, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/test2.rb
class Test2 < ApplicationRecord
end

app/models/test_master.rb
class TestMaster < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: 'desc')
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def new
    @post = Post.new
  end
  
  def create
    # render plain: params[:post].inspect
    # save
    @post = Post.new(post_params)
    if @post.save
      # redirect
      redirect_to posts_path
    else
      render 'new'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end
    
  def destroy
     @post = Post.find(params[:id])
     @post.destroy
     redirect_to posts_path
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/test1_controller.rb
class Test1Controller < ApplicationController
  def index
  end
end

app/controllers/test2s_controller.rb
class Test2sController < ApplicationController
  
  require 'date'
  
  def index
    
    # ユーザーが回答することで埋まっていく）
    # TODO 回答状況によって出題を変更する
    # TestMasterからtestを作成する
    test_num = Test2.maximum(:test_num).to_i + 1
    word_num = 0
    @test2 = createTestByTestMaster(test_num, word_num)
    
    # 開始時刻を記録する
    @test2.start_datetime = DateTime.now
    
    # テストをDBに保存する
    @test2.save
  end
  
  def create
    @test2s = Test2.all
  end
  
  def show
    # 問題番号を取得する
    # TODO ブラウザバックで2個前の問題に戻ってしまう。
    @test2 = Test2.find_by(id: params[:id])
    logger.debug(@test2.inspect)
  end
  
  def update
    # 問題番号を取得する
    @test2 = Test2.find_by(id: params[:id])
    # 回答をsaveする
    
    @test2.user_answer = params[:test2][:user_answer]
    
    @test2.end_datetime = DateTime.now
    @test2.save
    
    # 次の問題のIDを設定する
    word_num = @test2.word_num.to_i + 1
    test_num = @test2.test_num.to_i
    # IDが最大出題数を超えていたら結果ページに遷移する
    if word_num.to_i > 9 then
      redirect_to :controller => 'results', :action => 'index', :test_num => @test2.test_num
    # IDが最大出題数を超えていなければ次の問題を変数に格納する
    else      
      # TestMasterからtestを作成する
      @test2 = createTestByTestMaster(test_num.to_i, word_num.to_i)
      # 開始時刻を記録する
      @test2.start_datetime = DateTime.now
      # テストをDBに保存する
      @test2.save
    end
  end
  def createTestByTestMaster(test_num, word_num)
    # （仮）問題を取得する（この時点ではすべてのカラムが埋められていない
    # ユーザーが回答することで埋まっていく）
    test2 = Test2.new
    
    # 最初の問題を変数に格納する
    randomNumber = rand(0..2801)
    test_master = TestMaster.find(randomNumber)
    
    # testを作成する
    test2.word = test_master.word
    test2.answer1 = test_master.answer1
    test2.answer2 = test_master.answer2
    test2.answer3 = test_master.answer3
    test2.answer4 = test_master.answer4

    test2.right_answer = test_master.right_answer
    test2.test_num = test_num.to_i
    test2.word_num = word_num.to_i
    
    return test2
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
      
  end
  
  private
    def user_params
      params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test1_helper.rb
module Test1Helper
end

app/helpers/test2s_helper.rb
module Test2sHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  #引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url,alt: user.name, class:"gravatar")
  end
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<p>
  <%= f.text_field :title, placeholder: 'enter title' %>
  <% if @post.errors.messages[:title].any?  %>
  <span class="error"><%= @post.errors.messages[:title][0] %></span>
  <% end %>
</p>
<p>
  <%= f.text_area :body, placeholder: 'enter body text' %>
  <% if @post.errors.messages[:body].any?  %>
  <span class="error"><%= @post.errors.messages[:body][0] %></span>
  <% end %>
</p>
<p>
  <%= f.submit 'SUBMIT'%>
</p>

<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1><%= link_to 'START', test2s_path %></h1>
<!-- このページは使わなくなった→コード消すのもったいないから残しておく -->
<!-- <div id="wrapper" class="divided">
  <section class="banner style1 orient-left content-align-left image-position-right fullscreen onload-image-fade-in onload-content-fade-right">
    <div class="content">
      <h2>
        <%= link_to 'Add new', new_post_path, class: 'header-menu' %>
        My Posts
      </h2>
      <ul class="actions vertical">
        <% @posts.each do |post| %>
        <li>
          <%= link_to post.title, post_path(post) %>
          <%= link_to '[Edit]', edit_post_path(post), class: 'command'%>
          <%= link_to '[X]', post_path(post), 
          method: :delete,
          class: 'command',
          data:{ confirm: 'Sure?' } %>
        </li>
        <% end %>
      </ul>
    </div>
  </section>
</div> -->

app/views/posts/new.html.erb
<h2>Add New Post</h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= simple_format @post.body %></p>

<h3>Comments</h3>

<% if @post.comments.any? %>
<ul>
  <% @post.comments.each do |comment| %>
  <li>
    <%= comment.body %>
    <%= link_to '[X]', post_comment_path(@post, comment), 
    method: :delete,
    class: 'command',
    data:{ confirm: 'Sure?' } %>
  </li>
  <% end %>
</ul>
<% end %>

<%= form_for ([@post,@post.comments.build])  do |f| %>
<p>
  <%= f.text_field :body %>
</p>
<p>
  <%= f.submit %>
</p>

<% end %>

app/views/test2s/index.html.erb
<h2><%= link_to 'RESTART' , test2s_path %></h2>
<!-- indexのviewと完全に同じだからどっちかに統一させる -->
<h3><%= @test2.word_num.to_i + 1 %> / 10</h3>
<h1><%= @test2.word %></h1>

<%= form_for @test2 ,html: {name: 'test2_form'} do |f| %>
  <%= f.hidden_field :id, :id => 'id' , :value => @test2.id %>
  <%= f.hidden_field :word, :id => 'word' , :value => @test2.word %>
  <%= f.hidden_field :test_num, :id => 'test_num', :value => @test2.test_num %>
  <%= f.hidden_field :word_num, :id => 'word_num', :value => @test2.word_num %>
  <%= f.hidden_field :user_answer, :id => 'user_answer'%>
  
  <ul class="actions vertical">
    
    <li><%= f.button @test2.answer1, :type => 'button', :class =>'big wide smooth-scroll-middle', :name => 'user_answer',  onclick: "disp('answer1')"%></li>
    <%= hidden_field_tag 'answer1', @test2.answer1 %>  
    
    <li><%= f.button @test2.answer2, :type => 'submit', :class =>'big wide smooth-scroll-middle', :name => 'user_answer',  onclick: "disp('answer2')" %></li>
    <%= hidden_field_tag 'answer2', @test2.answer2 %>
    
    <li><%= f.button @test2.answer3, :type => 'submit', :class =>'big wide smooth-scroll-middle', :name => 'user_answer',  onclick: "disp('answer3')" %></li>
    <%= hidden_field_tag 'answer3', @test2.answer3 %>
    
    <li><%= f.button @test2.answer4, :type => 'submit', :class =>'big wide smooth-scroll-middle', :name => 'user_answer',  onclick: "disp('answer4')" %></li>
    <%= hidden_field_tag 'answer4', @test2.answer4 %>
  </ul>

  <%= javascript_tag do %>
  function disp(answer){
    var user_answer = document.getElementById(answer).value;
    document.getElementById('user_answer').value = user_answer;
    document.test2_form.submit()
  }
  <% end %>

<% end %>

app/views/test2s/show.html.erb
<h2><%= link_to 'RESTART' , test2s_path %></h2>
<!-- indexのviewと完全に同じだからどっちかに統一させる -->
<h3><%= @test2.word_num.to_i + 1 %> / 10</h3>
<h1><%= @test2.word %></h1>

<%= form_for @test2 ,html: {name: 'test2_form'} do |f| %>
  <%= f.hidden_field :id, :id => 'id' , :value => @test2.id %>
  <%= f.hidden_field :word, :id => 'word' , :value => @test2.word %>
  <%= f.hidden_field :test_num, :id => 'test_num', :value => @test2.test_num %>
  <%= f.hidden_field :word_num, :id => 'word_num', :value => @test2.word_num %>
  <%= f.hidden_field :user_answer, :id => 'user_answer'%>
  
  <ul class="actions vertical">
    
    <li><%= f.button @test2.answer1, :type => 'button', :class =>'big wide smooth-scroll-middle', :name => 'user_answer',  onclick: "disp('answer1')"%></li>
    <%= hidden_field_tag 'answer1', @test2.answer1 %>  
    
    <li><%= f.button @test2.answer2, :type => 'submit', :class =>'big wide smooth-scroll-middle', :name => 'user_answer',  onclick: "disp('answer2')" %></li>
    <%= hidden_field_tag 'answer2', @test2.answer2 %>
    
    <li><%= f.button @test2.answer3, :type => 'submit', :class =>'big wide smooth-scroll-middle', :name => 'user_answer',  onclick: "disp('answer3')" %></li>
    <%= hidden_field_tag 'answer3', @test2.answer3 %>
    
    <li><%= f.button @test2.answer4, :type => 'submit', :class =>'big wide smooth-scroll-middle', :name => 'user_answer',  onclick: "disp('answer4')" %></li>
    <%= hidden_field_tag 'answer4', @test2.answer4 %>
  </ul>

  <%= javascript_tag do %>
  function disp(answer){
    var user_answer = document.getElementById(answer).value;
    document.getElementById('user_answer').value = user_answer;
    document.test2_form.submit()
  }
  <% end %>

<% end %>

app/views/test2s/update.html.erb
<h2><%= link_to 'RESTART' , test2s_path %></h2>
<!-- indexのviewと完全に同じだからどっちかに統一させる -->
<h3><%= @test2.word_num.to_i + 1 %> / 10</h3>
<h1><%= @test2.word %></h1>

<%= form_for @test2 ,html: {name: 'test2_form'} do |f| %>
  <%= f.hidden_field :id, :id => 'id' , :value => @test2.id %>
  <%= f.hidden_field :word, :id => 'word' , :value => @test2.word %>
  <%= f.hidden_field :test_num, :id => 'test_num', :value => @test2.test_num %>
  <%= f.hidden_field :word_num, :id => 'word_num', :value => @test2.word_num %>
  <%= f.hidden_field :user_answer, :id => 'user_answer'%>
  
  <ul class="actions vertical">
    
    <li><%= f.button @test2.answer1, :type => 'button', :class =>'big wide smooth-scroll-middle', :name => 'user_answer',  onclick: "disp('answer1')"%></li>
    <%= hidden_field_tag 'answer1', @test2.answer1 %>  
    
    <li><%= f.button @test2.answer2, :type => 'submit', :class =>'big wide smooth-scroll-middle', :name => 'user_answer',  onclick: "disp('answer2')" %></li>
    <%= hidden_field_tag 'answer2', @test2.answer2 %>
    
    <li><%= f.button @test2.answer3, :type => 'submit', :class =>'big wide smooth-scroll-middle', :name => 'user_answer',  onclick: "disp('answer3')" %></li>
    <%= hidden_field_tag 'answer3', @test2.answer3 %>
    
    <li><%= f.button @test2.answer4, :type => 'submit', :class =>'big wide smooth-scroll-middle', :name => 'user_answer',  onclick: "disp('answer4')" %></li>
    <%= hidden_field_tag 'answer4', @test2.answer4 %>
  </ul>

  <%= javascript_tag do %>
  function disp(answer){
    var user_answer = document.getElementById(answer).value;
    document.getElementById('user_answer').value = user_answer;
    document.test2_form.submit()
  }
  <% end %>

<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class=""col-md-4>
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
</aside>
<div>